# Generated by Django 4.2.4 on 2023-09-25 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
        ('investo_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptos',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.crypto'),
        ),
    ]
