# Generated by Django 4.2.4 on 2023-09-05 09:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investo_hub', '0002_portfolio_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptos',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cryptos',
            name='portfolio',
        ),
        migrations.AlterField(
            model_name='cryptos',
            name='amount',
            field=models.DecimalField(decimal_places=20, default=Decimal('0.0'), max_digits=40),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=20, default=Decimal('0.0'), max_digits=40),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='dollars',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Stocks',
        ),
    ]
